name: Manually triggered workflow
on:
  workflow_dispatch

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - id: test_branch
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/head/v\.*?rc ]]; then
            echo ${{ github.event.ref }}
            exit 0
          fi 
  generate-relationships:
    runs-on: ubuntu-latest
    needs: check_branch
    if: needs.check_branch.result == 'success'
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}
      - name: list files 
        run: |
          echo | ls *
