name: Make sure new PRs are sent to staging
on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - '!main'
      - '!v.**-rc'
      - 'staging'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hi 
        run : |
          echo "hi"