name: Make sure new PRs are sent to staging
on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - '!main'
      - '!v.**-rc'
      - 'staging'


jobs:
  check_permissions:
    runs-on: ubuntu-latest
    steps:
      - name: get_permission
        uses: octokit/request-action@v2.x
        id: get_permission
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: output
        run:  |
          ${{ fromJSON(steps.get_permission.outputs.data) }}
