name: Merge to staging
on: [pull_request]
  
jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: check-branch
        uses: a-b-r-o-w-n/check-base-branch-action@v1.1
        with:
          protected-branches: "main"
          default-branch: "staging"
      - name: Branch name
        run: |
          echo "${{ github.event.pull_request.head.sha }}"
          echo "${{ github.event.ref }}"

      
      
