name: Make sure new PRs are sent to staging
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - '!main'
      - '!v.**-rc'
      - 'staging'


jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          USER_CONTEXT: ${{ toJSON(github.event.pull_request.user.login) }}
          EVENT_CONTEXT: ${{ toJSON(github.event.pull_request.base.repo.full_name) }}
        run: |
          export user=$(echo $USER_CONTEXT | sed "s/\"//g")
          export repo=$(echo $EVENT_CONTEXT | sed "s/\"//g")
          echo "permissions_url="GET /repos/$repo/collaborators/$user/permission" >> $GITHUB_ENV
          echo $permissions_url
      - name: Get Permission 
        uses: octokit/request-action@v2.x
        id: get_permission
        with:
          route: ${env.permissions_url}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: output
        run:  |
          echo ${{ fromJson(steps.get_permission.outputs.data).role_name }} 
