name: Merge to staging
on:
  pull_request:
    branches:    
      - staging
jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    if: endsWith(github.event.pull_request.base.ref, '-rc')
    steps:
      - name: Hi 
        run: |
          echo "hello"

  

        

      
      
