name: Merge to staging
on: [pull_request]
  
jobs:
  check-base-branch:
    runs-on: ubuntu-latest

    steps:
      - name: check-branch
        run: |
          echo ${{ github.event.pull_request.base.ref }}
          echo ${{ github.head_ref }}

      
      
