name: Make sure new PRs are sent to staging
on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - '!main'
      - '!v.**-rc'
      - 'staging'


jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          USER_CONTEXT: ${{ toJSON(github.event.pull_request.user.login) }}
          EVENT_CONTEXT: ${{ toJSON(github.event.pull_request.base.repo.full_name) }}
        run: |
          echo $USER_CONTEXT
          echo $EVENT_CONTEXT
      - uses: octokit/request-action@v2.x
        id: get_permission
        with:
          route: GET /repos/ror-community/ror-records/collaborators/eshadatta-crossref/permission
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: output
        run:  |
          echo ${{ fromJson(steps.get_permission.outputs.data).role_name }} 
