name: Merge to staging
on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
     - 'staging'
     - '!main'
     
jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    if: endsWith(github.event.pull_request.base.ref, '-rc')
    steps:
      - name: Hi 
        run: |
          echo "hello"

  

        

      
      
