name: Valid files
on:
  push:
    branches:
      - "v.**-rc"
jobs:
  generate-relationships:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Download requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.23.0
          curl https://raw.githubusercontent.com/ror-community/ror-api/generate_relationships/rorapi/management/commands/generaterelationships.py -o generaterelationships.py
          python generaterelationships.py relationships.csv
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: \*.json, \*.csv
          commit_message: Apply changes