name: Valid files
on:
  push:
    branches:
      - "v.**-rc"
jobs:
  generate-relationships:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Modify value # Tried to modify the files based on existing testfile.txt
        run: |
          echo 'Add value2' >> testfile.txt
      - name: move to dir # Move the generated files into output folder
        run: |
          mkdir -p output
          yes| cp -rf testfile.txt ./output/
      - name: Print branch name
        id: extract_branch
        run: echo "::set-output name=BRANCH::$(echo ${GITHUB_REF##*/})"
      - name: Get branch name
        run: echo ${{ steps.extract_branch.outputs.BRANCH }}"
