name: Validate files
on:
  workflow_dispatch

jobs:
  validate-files:
    runs-on: ubuntu-latest
    if: github.event.ref != 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Checkout validation suite
        uses: actions/checkout@v2
        with:
          repository: ror-community/validation-suite
          path: validation-suite
      - name: Validate files
        id: validatefiles
        run: |
          mkdir files 
          cp *.json files/
          cd validation-suite
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python run_validations.py -i ../files/013mwvk56.json -p ../files/
        continue-on-error: true
      - name: Notify Slack
        if: always()
        uses: edge/simple-slack-notify@master
        with:
          channel: '#ror-curation-releases'
          color: 'good'
          text: 'Validating files for ${github.event.ref}'
          failure_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) validation failed.'
          success_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) validation succeeded'
          fields: |
            { "title": "Validation", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}